config/routes.rb
V8::Application.routes.draw do

  resources :options

  root :to => 'topics#index' 

  match 'guangpan' => 'pages#guangpan'
  match 'baodao' => 'pages#baodao'
  match 'zhinanzhen' => 'pages#zhinanzhen'
  match 'zhidao'  => "pages#zhidao"
  match 'xianchang'  => "pages#xianchang"
  match 'xianchang/page(/:page)'  => "pages#xianchang"
  match 'wangpan'  => "pages#wangpan"
  match 'xingxiang'  => "pages#xingxiang"
  match 'vip' => "pages#vip"
  match 'xingxiang' => "pages#xingxiang"
  match 'hezuo' => "pages#hezuo"

  
    
  
  
  resources  :discussions, :comments, :subjects

  
  resources :topics,:constraints => {:id => /\d+/}  do
    resources :comments
  end
  
  resources :classrooms do
    resources :discussions
  end

  resources :notes, :constraints => {:id => /\d+/} do
    resources :comments
  end

  resources :resources, :constraints => {:id => /\d+/} do
    resources :comments
  end

  resources :testings do
    resources :comments
  end

  resources :articles, :constraints => {:id => /\d+/} do
    resources :comments
  end
  
  resources :events do 
    resources :notes
  end
  
  resources :subjects do
    resources :events
  end

  resources :categories do
    resources :articles
    resources :resources
    resources :notes  
    resources :topics
  end
  
  resources :people do
    resources :subjects
  end
  
  match '/topics/search' => "topics#search", :as => :topic_search
  match '/notes/search' => "notes#search", :as => :note_search
  match '/resources/search' => "resources#search", :as => :resource_search
  match '/articles/search' => "articles#search", :as => :article_search
  
  
  
  match 'login' => 'sessions#new', :via => :get
  match 'login' => 'sessions#create', :via => :post
  match 'logout'  => 'sessions#destroy', :via => :delete
  match 'test'  =>  "testings#test", :via => :post 
  
  
  match '/classes/:id' => 'groups#show', :as => :group, :via => :get
  match '/classes/:id/topics/page(/:page)' => 'groups#show'
  match '/topics/page(/:page)' => 'topics#index'        
  match '/topics/:path/page(/:page)' => 'topics#index'
  
  
  
  match '/classes/:id'  => "groups#update", :as => :group, :via => :put
  match '/classes/:id'  => "groups#destroy", :as => :group, :via => :delete
  
  match '/classes'  => "groups#index", :as => :groups, :via => :get
  match '/classes'  => "groups#create", :as => :groups, :via => :post
  
  match '/classes/new'  => "groups#new", :as => :new_group, :via => :get
  match '/classes/:id/edit'  => "groups#edit", :as => :edit_group, :via => :get
    
  match '/classes/:group_id/topics/:id' => 'topics#show', :as => :class_topic

  
  
  match 'resources/:path' => "resources#index", :as => :category_resources
  match 'notes/:path' => "notes#index", :as => :category_notes
  match 'articles/:path' => "articles#index", :as => :category_articles
  match 'topics/:path' => "topics#index", :as => :category_topics
  
  
  match '/events/page(/:page)' => 'events#index' 
  
  match '/notes/page(/:page)' => 'notes#index'
  match '/notes/:path/page(/:page)' => 'notes#index'
  
  
  match '/articles/page(/:page)' => 'articles#index'
  match '/articles/:path/page(/:page)' => 'articles#index'
  
  
  match '/resources/page(/:page)' => 'resources#index'
  match '/resources/:path/page(/:page)' => 'resources#index'
  
  
  match '/testings/page(/:page)' => 'testings#index'
  match '/apps' => 'testings#index'
  match '/apps/:id' => 'testings#show'
  match '/apps/page(/:page)' => 'testings#index'
  
  match '/classrooms/:id/page(/:page)' => 'classrooms#show'
  match '/discussions/page(/:page)' => 'discussions#index'
  
  
  match '/people/page(/:page)' => 'people#index'
  

  
  
  

  namespace :admin do
    resources :people
  end

  

  match '*path' => proc { |env| Rails.env.development? ? (raise ActionController::RoutingError, %{No route matches "#{env["PATH_INFO"]}"}) : ApplicationController.action(:render_not_found).call(env) }  
  
end

app/models/note.rb
# -*- encoding : utf-8 -*-
class Note < ActiveRecord::Base
  belongs_to :person
  belongs_to :category
  has_many :comments, :as => :commable
  paginates_per 10
  validates :title, :length => {:in => 1..50, :message => "标题限制1到50字"}
  validates :content, :length => {:in => 10..1000, :too_short => "惯例内容至少10个字", :too_long => "写的太多了，请简明扼要，字数限制500"}

  
  def remove_hint_span
    self.content = self.content.gsub(/<span\sclass=\'usage_pinglun\'>/,"").gsub(/<\/span>/,"")
  end
  
  before_save :add_color_to_tag, :change_url

  protected
  def add_color_to_tag
    tag_match_data            = self.content.match(/@\S*/) 
    if tag_match_data
      tag                     = tag_match_data[0]
      self.content            = self.content.sub!(tag, "<span class='usage_pinglun'>#{tag}</span>")
    end
  end

  def change_url
    match_data            = self.content.match(/\[url\](.+)\[\/url\]/) 
    if match_data
      url                     = match_data[1]  #匹配里面的url
      self.content            = self.content.gsub(match_data[0], "<a href='#{url.include?("http") ? url : "http://"+url}' target='_blank'>#{url}</a>")
    end
  end
  
end

app/controllers/notes_controller.rb
# -*- encoding : utf-8 -*-
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.json
  skip_before_filter :is_login?, :only => [:index, :show, :search]
  before_filter :only_member_can_do, :except => [:index, :show, :search]

  def index
    @note = Note.new
    @path = params[:path]
    @categories = Category.where(:typeable => "Note").includes(:notes).order("order_number")
    if params[:path]
      @notes = Category.where("typeable=? and path=?","Note",params[:path])[0].notes.includes(:person).order("created_at desc").page(params[:page])      
    else
	    @notes = Note.includes(:person).order("created_at desc").page(params[:page])      
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
    
  end

  def search
    if params[:query] == "" || params[:query].is_a?(NilClass)
      @notes = []
      flash.now[:notice] = "请输入搜索词语"
      render :search 
    else 
      @notes = Note.where("title LIKE ?", "%"+params[:query]+"%").order("created_at desc").page(params[:page])
      respond_to do |format|
        format.html # search.html.erb
        format.json { render json: @notes }
      end
    end
    
  end
  
  def new
    @note = Note.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end
    
  def show
    @note = Note.find(params[:id])
    @latest_notes = Note.order("created_at desc").limit(10)
    @comments = @note.comments
    @comment = Comment.new
    # unless is_member?
    #    if (35..37).include?(@note.category_id)
    #      redirect_to :guangpan, notice: "高级惯例只有学员可浏览" and return
    #    end
    #  end  
    
    @categories = Category.where(:typeable => "Note").order("order_number")
    
    respond_to do |format|
      format.html
      format.json {render json: @note}
    end
    
  end
  # GET /notes/1/edit
  def edit
    if is_admin?
      @note = Note.find(params[:id])
    else
      @note = current_person.notes.find(params[:id])
    end
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = current_person.notes.build(params[:note])

    respond_to do |format|
      if @note.save
        @note.person.update_column(:score,@note.person.score+3)
        format.html { redirect_to @note, notice: '创建成功' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
        
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    if is_admin?
      @note = Note.find(params[:id])
    else
      @note = current_person.notes.find(params[:id])
    end

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: '更新成功' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    if is_admin?
      @note = Note.find(params[:id])
    else
      @note = current_person.notes.find(params[:id])
    end
    
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end 
end

app/helpers/notes_helper.rb
# -*- encoding : utf-8 -*-
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
			<div class="alert">
			  <button type="button" class="close" data-dismiss="alert">&times;</button>
			  <h4><%= @note.errors.count.to_s+"个错误" %> :</h4>
	      <ul>
	      <% @note.errors.full_messages.each do |msg| %>
	        <li><%= format_error(msg) %></li>
	      <% end %>
	      </ul>
			</div>
	  <% end %>

  <div class="field">
    <%= f.label :category_id, "选择阶段" %>
    <%= f.select :category_id, collect_note_categories_for_select, :selected => @note.new_record? ? 33 : @note.category.id %>
  </div>


  <div class="field">
    <%= f.label :title, "标题" %>
    <%= f.text_field :title,  :class => "input-xxlarge" %>
  </div>

  <div class="field">
    <%= f.label :content, "内容(10到500字)" %>
    <%= f.text_area :content, :size  => "82x10", :class => "input-xxlarge", :value => @note.new_record? ? "" : @note.remove_hint_span %>
  </div>
	<div class="help-block">换行后,添加@标记,后面可以写适合场合等(请看已创建的惯例).</div>
  <div class="actions">
    <%= f.submit "提交", :class => "btn btn-primary ie6-btn" %>
		<%= link_to '取消', topics_path, :class => "btn cancel" %>

  </div>
<% end %>

app/views/notes/edit.html.erb
<h4>编辑惯例</h4>

<%= render 'form' %>

<%= link_to '取消', notes_path %>

app/views/notes/index.html.erb
<% content_for :title,"泡妞话术惯例库,追女孩子的技巧,追女孩子的短信都在这里" %>
<% content_for :keywords,"话术,惯例库,追女孩子的技巧,追女孩子的短信,追女孩子的话,追女孩子的方法,追女生,追女生技巧" %>
<% content_for :description,"你还在不知道怎么和女孩说话吗?你还在寻找追女孩子的技巧吗?也许你还在收集追女孩子的短信,一切都在这里.包括追女生技巧.追女秘籍,追女孩子的甜言蜜语." %>



<div class="row ie6-row">
	
	
	
	<div class="span9">
		
		<% if notice %>
			<div class="alert">
			  <button type="button" class="close" data-dismiss="alert">&times;</button>
			  <%= notice %>
			</div>
		<% end %>  
		<%= link_to "+ 提交惯例",:new_note, :class => "btn btn-success pull-left" %>

		<%= form_tag :note_search, :class => "form-search pull-right" do |f| %>
	    <%= text_field_tag :query,nil, :class => "input-medium search-query" %>
  		<button type="submit" class="btn btn-primary">搜索惯例</button>
		<% end %>
		<br />
		<br />
		
		<h4>最新惯例</h4>

		
		<% @notes.each do |note| %>
			<div class="media">
			  <a class="pull-left" href="#">
					<%= image_tag note.person.avatar.url(:thumb),:class => "media-object" %>
			  </a>
			  <div class="media-body">
			    <h4 class="media-heading"><%= link_to note.title, note, :target => "_blank" %></h4>
			    <div class="media">
						发布:<%= link_to note.person.nick_name, note.person %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;阶段:<%= link_to note.category.name, category_notes_path(:path => note.category.path) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;时间:<%= note.created_at.to_date.to_s %>
						<br />
						<br /> 
						<% if !is_member?  and (35..37).include?(note.category_id)%>
							抱歉,你不能查看vip栏目,请联系qq:399906796, <%= link_to "开通vip学员", "/vip" %>
						<% else %>
						 <%= simple_format note.content %>
						<% end %>
						<%= link_to "评论(#{note.comments.size})", note, :target => "_blank",:class => "pull-right"  %>
			    </div>
			  </div>
			</div>
			<hr />
			
		<% end %>
		
		<%= paginate @notes %>		

	</div>
	
	<div class="span3"> 
		
		<ul class="nav nav-tabs nav-stacked">
			<li <%="class=active" if @path == nil  %>><%= link_to  notes_path do %><i class="icon-chevron-right pull-right"></i>所有阶段<% end %></li>
			<% @categories.each do |category| %>
			<li <%="class=active" if @path == category.path  %>>
				<%= link_to category_notes_path(:path => category.path) do %>
					<i class="icon-chevron-right pull-right"></i> <%=  category.name %>(<%= category.notes.size %>)   
				<% end %>
			</li>
			<% end %>
		</ul>

	</div>
</div>

app/views/notes/new.html.erb
<div class="row">
	<div class="span8">

	<h4>增加惯例</h4>

	<%= render 'form' %>

	</div>
	<div class="span4">

	<%= link_to '<<返回', notes_path %>
	</div>
</div>

app/views/notes/search.html.erb
<% content_for :title,"惯例搜索" %>
<% content_for :keywords,"泡妞学问答,泡妞问题,泡妞案例分享." %>
<% content_for :description, "惯例搜索" %>

<div class="row">		
	<div class="span8">
		<% if notice %>
			<div class="alert">
			  <button type="button" class="close" data-dismiss="alert">&times;</button>
			  <%= notice %>
			</div>
		<% end %>
		<div class="row">
			<div class="span8">
				<%= form_tag :note_search, :class => "form-search" do |f| %>
			    <%= text_field_tag :query,params[:query], :class => "input-medium search-query" %>
		  		<button type="submit" class="btn btn-primary">搜索惯例</button>
				<% end %>
			</div>
		</div>
		
		<h4>惯例搜索:<%= params[:query] %></h4>
		<table id="search_results" class="table table-condensed">
			<tbody>
				<% @notes.each do |note| %>
				<tr>
					<td class="title"><%= link_to note.title, note , :target => "_blank"%></td>
					<td class="created-at"><%= time_ago_in_words(note.created_at) %>发表</td>
					<td class="nick_name"><%= link_to note.person.nick_name, note.person %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<% unless @notes == [] %>
			<%= paginate @notes %>		
		<% end %>
	</div>
	
	
		
	
	
	<div class="span4">
		<%= link_to "返回<<", notes_path %>
	</div>

</div>

app/views/notes/show.html.erb
<% content_for :title, @note.title %>
<% content_for :keywords,"话术,惯例库,追女孩子的技巧,追女孩子的短信,追女孩子的话,追女孩子的方法,追女生,追女生技巧" %>
<% content_for :description, @note.content %>




<div class="row">
	<div class="span8">
			<% if notice %>
				<div class="alert">
				  <button type="button" class="close" data-dismiss="alert">&times;</button>
				  <%= notice %>
				</div>
			<% end %>
			<div class="media">
			  <a class="pull-left" href="#">
					<%= image_tag @note.person.avatar.url(:thumb),:class => "media-object" %>
			  </a>
			  <div class="media-body">
			    <h4 class="media-heading"><%= link_to @note.title, @note, :target => "_blank" %></h4>
			    <div class="media">
						发布:<%= link_to @note.person.nick_name, @note.person %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;阶段:<%= link_to @note.category.name, category_notes_path(:path => @note.category.path) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;时间:<%= @note.created_at.to_date.to_s %>
						<br />
						<br /> 
						<% if !is_member? and (35..37).include?(@note.category_id)%>
							抱歉,你不能查看vip栏目,请联系qq:399906796, <%= link_to "开通vip学员", "/vip" %>
						<% else %>
						 <%= simple_format @note.content %>
						<% end %>
						<% if can_delete?(@note) %>
							<%= link_to '编辑', edit_note_path(@note) %>
							<%= link_to '删除', @note, :data => { :confirm => '确定删除' }, method: :delete %>
						<% end %>
						<%= render :partial => "share/bdshare" %>	
						
			    </div>
			  </div>
			</div>
			<br />
			<h4>所有评论</h4>
		
			<hr />
			
			<% @comments.each do |comment| %>
				<%= render comment %>
			
			<% end %>
			
			<%= render :partial => "comments/form", :locals => { :comment => @comment, :commable_type => "Note", :commable_id => @note.id } %>

	</div>

	<div class="span4">
		<%= link_to "返回<<", :back %>
		<hr />
		<h4>最近惯例</h4>
		<ul>
		<% @latest_notes.each do |note| %>
			<li><%= link_to note.title, note %></li>
		<% end %>
		</ul>
	</div>
	
	
</div>