config/routes.rb
V8::Application.routes.draw do

  resources :options

  root :to => 'topics#index' 

  match 'guangpan' => 'pages#guangpan'
  match 'baodao' => 'pages#baodao'
  match 'zhinanzhen' => 'pages#zhinanzhen'
  match 'zhidao'  => "pages#zhidao"
  match 'xianchang'  => "pages#xianchang"
  match 'xianchang/page(/:page)'  => "pages#xianchang"
  match 'wangpan'  => "pages#wangpan"
  match 'xingxiang'  => "pages#xingxiang"
  match 'vip' => "pages#vip"
  match 'xingxiang' => "pages#xingxiang"
  match 'hezuo' => "pages#hezuo"

  
    
  
  
  resources  :discussions, :comments, :subjects

  
  resources :topics,:constraints => {:id => /\d+/}  do
    resources :comments
  end
  
  resources :classrooms do
    resources :discussions
  end

  resources :notes, :constraints => {:id => /\d+/} do
    resources :comments
  end

  resources :resources, :constraints => {:id => /\d+/} do
    resources :comments
  end

  resources :testings do
    resources :comments
  end

  resources :articles, :constraints => {:id => /\d+/} do
    resources :comments
  end
  
  resources :events do 
    resources :notes
  end
  
  resources :subjects do
    resources :events
  end

  resources :categories do
    resources :articles
    resources :resources
    resources :notes  
    resources :topics
  end
  
  resources :people do
    resources :subjects
  end
  
  match '/topics/search' => "topics#search", :as => :topic_search
  match '/notes/search' => "notes#search", :as => :note_search
  match '/resources/search' => "resources#search", :as => :resource_search
  match '/articles/search' => "articles#search", :as => :article_search
  
  
  
  match 'login' => 'sessions#new', :via => :get
  match 'login' => 'sessions#create', :via => :post
  match 'logout'  => 'sessions#destroy', :via => :delete
  match 'test'  =>  "testings#test", :via => :post 
  
  
  match '/classes/:id' => 'groups#show', :as => :group, :via => :get
  match '/classes/:id/topics/page(/:page)' => 'groups#show'
  match '/topics/page(/:page)' => 'topics#index'        
  match '/topics/:path/page(/:page)' => 'topics#index'
  
  
  
  match '/classes/:id'  => "groups#update", :as => :group, :via => :put
  match '/classes/:id'  => "groups#destroy", :as => :group, :via => :delete
  
  match '/classes'  => "groups#index", :as => :groups, :via => :get
  match '/classes'  => "groups#create", :as => :groups, :via => :post
  
  match '/classes/new'  => "groups#new", :as => :new_group, :via => :get
  match '/classes/:id/edit'  => "groups#edit", :as => :edit_group, :via => :get
    
  match '/classes/:group_id/topics/:id' => 'topics#show', :as => :class_topic

  
  
  match 'resources/:path' => "resources#index", :as => :category_resources
  match 'notes/:path' => "notes#index", :as => :category_notes
  match 'articles/:path' => "articles#index", :as => :category_articles
  match 'topics/:path' => "topics#index", :as => :category_topics
  
  
  match '/events/page(/:page)' => 'events#index' 
  
  match '/notes/page(/:page)' => 'notes#index'
  match '/notes/:path/page(/:page)' => 'notes#index'
  
  
  match '/articles/page(/:page)' => 'articles#index'
  match '/articles/:path/page(/:page)' => 'articles#index'
  
  
  match '/resources/page(/:page)' => 'resources#index'
  match '/resources/:path/page(/:page)' => 'resources#index'
  
  
  match '/testings/page(/:page)' => 'testings#index'
  match '/apps' => 'testings#index'
  match '/apps/:id' => 'testings#show'
  match '/apps/page(/:page)' => 'testings#index'
  
  match '/classrooms/:id/page(/:page)' => 'classrooms#show'
  match '/discussions/page(/:page)' => 'discussions#index'
  
  
  match '/people/page(/:page)' => 'people#index'
  

  
  
  

  namespace :admin do
    resources :people
  end

  

  match '*path' => proc { |env| Rails.env.development? ? (raise ActionController::RoutingError, %{No route matches "#{env["PATH_INFO"]}"}) : ApplicationController.action(:render_not_found).call(env) }  
  
end

app/models/topic.rb
# -*- encoding : utf-8 -*-
class Topic < ActiveRecord::Base
  has_many :comments, :as => :commable, :dependent => :destroy
  belongs_to :categories
  belongs_to :group
  belongs_to :person
  belongs_to :last_replied_person, :class_name => "Person", :foreign_key => "last_replied_by"
  has_many :assets, :dependent => :destroy
  accepts_nested_attributes_for :assets, :allow_destroy => true
  
  has_many :attachments, :conditions => "assets.asset_type = 'attachment'", :class_name => "Asset"
  
  paginates_per 50
  validates :title, :length => {:in => 1..200, :message => "标题限制1到50字"}
  validates :content, :length => {:in => 1..200000, :too_short => "内容写的太少了", :too_long => "写的太多了，请简洁"}
  
  
  
  before_save :change_url
  protected
  def change_url
    match_data            = self.content.match(/\[url\](.+)\[\/url\]/) 
    if match_data
      url                     = match_data[1]  #匹配里面的url
      self.content            = self.content.gsub(match_data[0], "<a href='#{url.include?("http") ? url : "http://"+url}' target='_blank'>#{url}</a>")
    end
  end    
  #      
   
  def find_match_asset(str) 
      a = str
       self.assets.each do |asset|
            if str.include?(asset.image_file_name) 
              a =   "<img src='#{asset.image.url(:medium)}' />" 
            end
       end 
       a
  end
  
end

app/controllers/topics_controller.rb
# -*- encoding : utf-8 -*-
class TopicsController < ApplicationController
  # GET /topics
  # GET /topics.json
  
  skip_before_filter :is_login?, :only => [:index, :show, :search]
  # before_filter :only_member_can_do, :except => [:index, :show, :search]

  def index                         
    @categories = Category.where(:typeable => "Topic").order("order_number")
    @group = Group.find(1)
    if params[:path]
      @topics = Category.where("typeable = ? and path=?", "Topic", params[:path])[0].topics.includes(:person).includes(:last_replied_person).includes(:assets).includes(:comments).order("last_replied_at desc").page(params[:page])  
    else
      @topics =Topic.includes(:person).includes(:last_replied_person).includes(:comments).order("last_replied_at desc").page(params[:page]) 
    end                                          
    @people = Person.where(["role = ? or role = ? or role =? or role = ?", "学员", "老师", "助教", "admin"]).order("score desc").limit(12)

    @notes = Note.order("created_at desc").limit(10)
    # @testings = Testing.order("created_at desc").limit(10)
    
    @resources = Resource.order("created_at desc").limit(10)
    @articles = Article.order("created_at desc").limit(10)
    @events = Event.order("created_at desc").limit(10)         

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end
  
  def search
    if params[:query] == "" || params[:query].is_a?(NilClass)
      @topics = []
      flash.now[:notice] = "请输入搜索词语"
      render :search 
    else 
      @topics = Topic.where("title LIKE ?", "%"+params[:query]+"%").order("created_at desc").page(params[:page])
      respond_to do |format|
        format.html # search.html.erb
        format.json { render json: @topics }
      end
    end
    
  end

  
  def show
    @topic = Topic.find(params[:id])
    @latest_topics = Topic.order("last_replied_at desc").limit(10)   
    @comments = @topic.comments
    @comment = Comment.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end    
  end

  
  def new             
    @topic = Topic.new   
    5.times { @topic.assets.build }
    @topic.group = Group.find(1)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end
  
  # GET /topics/1/edit
  def edit
    if is_admin?
      @topic = Topic.find(params[:id])  
    else
      @topic = current_person.topics.find(params[:id])
    end                                      
    (5 - @topic.assets.length).times { @topic.assets.build }
    @group = @topic.group
  end


  # POST /topics
  # POST /topics.json
  def create
    @topic = current_person.topics.build(params[:topic])
    @topic.last_replied_at = Time.now
    respond_to do |format|
      if @topic.save
        @topic.person.update_column(:score,@topic.person.score+2)
        format.html { redirect_to @topic, notice: '创建成功' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    if is_admin?
      @topic = Topic.find(params[:id])
    else
      @topic = current_person.topics.find(params[:id])
    end

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: '更新成功' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    if is_admin?
      @topic = Topic.find(params[:id])
    else
      @topic = current_person.topics.find(params[:id])
    end
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_path }
      format.json { head :no_content }
    end
  end  

  
end

app/helpers/topics_helper.rb
# -*- encoding : utf-8 -*-
module TopicsHelper
end

app/views/topics/_form.html.erb
<script>
	$(document).ready(function() {
		$('.newPaperclipFiles').hide();
	 	$('.add_image').click(function() {
				$('.newPaperclipFiles').slideToggle();
		 });   
	});               
</script>
		
	<%= form_for(@topic, :html => { :multipart => true }) do |f| %>
	<% if @topic.errors.any? %>
			<div class="alert">
			  <button type="button" class="close" data-dismiss="alert">&times;</button>
			  <h4><%= @topic.errors.count.to_s+"个错误" %> :</h4>
	      <ul>
	      <% @topic.errors.full_messages.each do |msg| %>
	        <li><%= format_error(msg) %></li>
	      <% end %>
	      </ul>
			</div>
	  <% end %>

  
  <div class="field">
    <%= f.label :title, "1到2句话概括问题(不超过50字)" %>
    <%= f.text_field :title, :class => "input-xxlarge" %>
  </div>
  <div class="field">
    <%= f.label :content, "详细内容(至少100字,最多1000字,便于分析)" %>
    <%= f.text_area :content, :size => "72x11", :class => "input-xxlarge" %>
  </div>
                    
 	<%= link_to "图片附件(最多5张)","#",:class => "add_image"%> <small>每张图不能超过500kb</small>
	<div class="newPaperclipFiles">
			<% if is_member? %>
	        <%= f.fields_for :assets do |asset| %>    
	           <% if asset.object.new_record? %>      
	 							 <br /> 
	              <%= asset.file_field :image, :accept => "image/gif, image/jpeg,image/png" %> 
						 	<% else asset.object.new_record? %> 
								
						 		<%= image_tag(asset.object.image.url(:thumb) ) %>  
		          	<%= asset.check_box :_destroy  %> <small>勾选删除</small>                  
							<% end %>     
								
	       <% end %>
			<% else %>
			<div class="alert">
			  <button type="button" class="close" data-dismiss="alert">&times;</button>
				只有学员才可以添加图片
			</div>
			<% end %>
  </div>     



  <div class="field">
    <%= f.hidden_field :group_id, :value => @topic.group.id  %>
  </div>


  <div class="actions">           
		<br />
    <%= f.submit "提交", :class => "btn btn-primary ie6-btn" %>
		<%= link_to '取消', topics_path, :class => "btn cancel" %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<div class="row">
	<div class="span8">

	<h4>编辑帖子</h4>

	<%= render 'form' %>

	</div>
	<div class="span4">

	<%= link_to '<<返回', topics_path %>
	</div>
</div>

app/views/topics/index.html.erb
<% content_for :title,"pua课程网-1个月提高你的情商" %>
<% content_for :keywords,"泡妞话术,惯例库,追女孩子的技巧,追女孩子的短信,追女孩子的话,追女孩子的方法,追女生,追女生技巧" %>
<% content_for :description,"pua课程网,致力于提高你的情商,情感求助,有问必答,通过在此网站的学习,1个月后,情商翻倍!" %>


<div class="row ie6-row">
	
	<div class="span8">
		<% if notice %>
			<div class="alert">
			  <button type="button" class="close" data-dismiss="alert">&times;</button>
			  <%= notice %>
			</div>
		<% end %>
		
		<%= link_to "+ 提问",:new_topic, :class => "btn btn-success pull-left" %>
	           
		
		<%= form_tag :topic_search, :class => "form-search pull-right" do |f| %>
	    <%= text_field_tag :query,nil, :class => "input-medium search-query" %>
  		<button type="submit" class="btn btn-primary">搜索问题</button>
		<% end %>       
		<br />
		<br />
		<br />
 		<ul class="ie6-label clearfix" > 
			<li class="label label-info"><%= link_to "所有节点", topics_path %></li>
			<% @categories.each do |c| %>
				<li class="label label-info">
					<%= link_to c.name, category_topics_path(:path => c.path) %>
				</li>
			<% end %>         
		</ul>            
	
		<div id="topics">
			<% @topics.each do |topic| %>
				<div class="media">
				  <a class="pull-left" href="#">
						<%= image_tag topic.person.avatar.url(:thumb),:class => "media-object" %>
				  </a>
				  <div class="media-body">
				    <p class="media-heading"><%= link_to truncate(topic.title,:length => 30), topic, :target => "_blank" %>   <span class="pull-right badge badge-info"><%= topic.comments.size %></span>
							<% if topic.assets.size != 0 %>
								<span>
									<% topic.assets[0,2].each do |asset|  %>
		              	<%= link_to(image_tag(asset.image.url(:thumb), :class => "pull-right",:style => "margin-right:5px;"),topic)  %>   
									<% end %>
								</span>
							<% end %>     
						</p>
				    <div class="media">
							<p class="help-block"><%= link_to topic.person.nick_name, topic.person %>(<%= link_to topic.person.city, people_path(:city =>topic.person.city ) %>)&nbsp;&nbsp;•&nbsp;&nbsp;
							<% if topic.comments.size > 0 %>
								最后由&nbsp;<%= link_to topic.last_replied_person.nick_name,topic.last_replied_person %>&nbsp;于<%= time_ago_in_words(topic.last_replied_at) %>回复 
								
							<% else %>
								    <%= time_ago_in_words(topic.created_at) %>发布
							<% end %>  
						
							</p>
				    </div>
				  </div>
				</div>
				<hr />
			                   
			<% end %>
		</div>			 
		<div class="ie6-pagination"> 	
		<%= paginate @topics %>		
		</div>
	</div>
	
	
	<div class="span4">
		<div class="media">
	 	  <a class="pull-left" href="#">
				<%= image_tag @group.avatar.url(:medium), :class => "media-object" %>
		  </a>
		  <div class="media-body">
		    <h4 class="media-heading">班级名:<%= @group.name %></h4>
		    <div class="media">
		      <p>
					  老师:<%= link_to @group.person.nick_name, @group.person %><br />
						助教1:
						助教2:
					</p>
			
					<% if can_delete?(@group) %>
						<%= link_to '编辑', edit_group_path(@group) %> 
					<% end %>
		    </div>
		  </div>
		</div>      
		<!-- 加上id是为了避免自动关闭       -->
		<div id="alert" class="alert">
		  <%= simple_format @group.description %>
		</div>
				
		<hr />              
		
		<h4>积分前12名:</h4>
		<div class="row">  			
		<% @people.each do |person| %>
			<div class="span1 people-row ie6-row-people">
				<div class="media">
					<div class="person-avatar">
						<%= link_to image_tag(person.avatar.url(:thumb), :class => "media-object"), person%>
					</div> 
				  <div class="media-body">
				    <div class="media">  
								<small>
							 		<%= link_to person.nick_name, person %>
								</small>     
				    </div>
				  </div>
				</div>
			</div>
		<% end %>  
		</div>		
	
		
		<%= link_to ">>所有学员", people_path %>
		
		
		<hr />
		
		<h4>最近发布资源:</h4>
		<ul>
			<% @resources.each do |resource| %>
				<li><%= image_tag resource.category.avatar.url(:thumb) %><%= link_to resource.title, resource %><br /></li>
			<% end %>				
		</ul>
		<%= link_to ">>所有资源", resources_path %>
		<hr />
		
	
		<h4>最近发布惯例:</h4>
		<ul>
			<% @notes.each do |note| %>
				<li><%= link_to note.title, note %><br /></li>
			<% end %>				
		</ul>
		<%= link_to ">>所有惯例", notes_path %>
		<hr />
		
	
		<h4>最近发布文章:</h4>
		<ul>
			<% @articles.each do |article| %>
				<li><%= link_to article.title, article %><br /></li>
			<% end %>				
		</ul>
		<%= link_to ">>所有文章", articles_path %>
		
		<hr />
		
		<h4>最近发布的培训聚会:</h4>
		<ul>
			<% @events.each do |event| %>
				<li><%= link_to event.name, event %><br /></li>
			<% end %>				
		</ul>
		<%= link_to ">>所有活动", events_path %>
		
		
	</div>

</div>

app/views/topics/new.erb
<div class="row">
	<div class="span8">

	<h4>发帖</h4>

	<%= render 'form' %>

	</div>
	<div class="span4">

	<%= link_to '<<返回', topics_path %>
	</div>
</div>

app/views/topics/search.html.erb
<% content_for :title,"话题搜索" %>
<% content_for :keywords,"泡妞学问答,泡妞问题,泡妞案例分享." %>
<% content_for :description, "话题搜索" %>

<div class="row">		
	<div class="span8">
		<% if notice %>
			<div class="alert">
			  <button type="button" class="close" data-dismiss="alert">&times;</button>
			  <%= notice %>
			</div>
		<% end %>
		<div class="row">
			<div class="span8">
				<%= form_tag :topic_search, :class => "form-search" do |f| %>
			    <%= text_field_tag :query,params[:query], :class => "input-medium search-query" %>
		  		<button type="submit" class="btn btn-primary">搜索问题</button>
				<% end %>
			</div>
		</div>
		
		<h4>问题搜索:<%= params[:query] %></h4>
		<table id="search_results" class="table table-condensed">
			<tbody>
				<% @topics.each do |topic| %>
				<tr>
					<td class="title"><%= link_to topic.title, topic , :target => "_blank"%></td>
					<td class="created-at"><%= time_ago_in_words(topic.created_at) %>发表</td>
					<td class="comments-size"><%= topic.comments.size %>回应</td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<% unless @topics == [] %>
			<%= paginate @topics %>		
		<% end %>
		
	</div>
	
	
		
	
	
	<div class="span4">
		<%= link_to "返回<<", topics_path %>
	</div>

</div>

app/views/topics/show.html.erb
<% content_for :title,@topic.title %>
<% content_for :keywords,"泡妞学问答,泡妞问题,泡妞案例分享." %>
<% content_for :description, truncate(@topic.content, :length => 300) %>

<div class="row">		
		<div class="span8">
				<% if notice %>
					<div class="alert">
					  <button type="button" class="close" data-dismiss="alert">&times;</button>
					  <%= notice %>
					</div>
				<% end %>
				<div class="media">
				  <a class="pull-left" href="#">
						<%= image_tag @topic.person.avatar.url(:thumb),:class => "media-object" %>
				  </a>
				  <div class="media-body">
				    <h4 class="media-heading"><%= link_to @topic.title, @topic, :target => "_blank" %></h4>
				    <div class="media">
							发布:<%= link_to @topic.person.nick_name, @topic.person %>(<%= link_to @topic.person.city, people_path(:city => @topic.person.city)%>)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;时间:<%= @topic.created_at.to_date.to_s %>
							<br />
							<br />
							<%= simple_format @topic.content %>  
						  <% unless @topic.assets.size == 0  %>           
								<% if session[:person_id] %>
									<% @topic.attachments.each do |asset| %>
			              <%= image_tag(asset.image.url(:medium))  %>
									<% end %>
								<% else %>     
									<% @topic.attachments.each do |asset| %>   
			              <%= image_tag(asset.image.url(:thumb)) %>
									<% end %>  
									<h5>注册后查看大图</h5>   
				       	<% end %>
							<% end %> 
							<div class="clearfix"></div>
							<br />
							<% if can_delete?(@topic) %>
								<%= link_to '编辑', edit_topic_path(@topic) %>
								<%= link_to '删除', @topic, :data => { :confirm => '确定删除' }, method: :delete %>
							<% end %>
							<%= render :partial => "share/bdshare" %>	
				    </div>
				  </div>
				</div>
				<br />
				<h4>所有回复(回复:+1积分)</h4>
				<hr />

				<% @comments.each do |comment| %>
					<%= render comment %>

				<% end %>

				<%= render :partial => "comments/form", :locals => { :comment => @comment, :commable_type => "Topic", :commable_id => @topic.id } %>

		</div>
		
	<div class="span4">
		<%= link_to "返回<<", :back %>
		<hr />
		<h4>最近话题</h4>
		<ul>
		<% @latest_topics.each do |topic| %>
			<li><%= link_to topic.title, topic %></li>
		<% end %>
		</ul>
	</div>

</div>