config/routes.rb
V8::Application.routes.draw do

  resources :options

  root :to => 'topics#index' 

  match 'guangpan' => 'pages#guangpan'
  match 'baodao' => 'pages#baodao'
  match 'zhinanzhen' => 'pages#zhinanzhen'
  match 'zhidao'  => "pages#zhidao"
  match 'xianchang'  => "pages#xianchang"
  match 'xianchang/page(/:page)'  => "pages#xianchang"
  match 'wangpan'  => "pages#wangpan"
  match 'xingxiang'  => "pages#xingxiang"
  match 'vip' => "pages#vip"
  match 'xingxiang' => "pages#xingxiang"
  match 'hezuo' => "pages#hezuo"

  
    
  
  
  resources  :discussions, :comments, :subjects

  
  resources :topics,:constraints => {:id => /\d+/}  do
    resources :comments
  end
  
  resources :classrooms do
    resources :discussions
  end

  resources :notes, :constraints => {:id => /\d+/} do
    resources :comments
  end

  resources :resources, :constraints => {:id => /\d+/} do
    resources :comments
  end

  resources :testings do
    resources :comments
  end

  resources :articles, :constraints => {:id => /\d+/} do
    resources :comments
  end
  
  resources :events do 
    resources :notes
  end
  
  resources :subjects do
    resources :events
  end

  resources :categories do
    resources :articles
    resources :resources
    resources :notes  
    resources :topics
  end
  
  resources :people do
    resources :subjects
  end
  
  match '/topics/search' => "topics#search", :as => :topic_search
  match '/notes/search' => "notes#search", :as => :note_search
  match '/resources/search' => "resources#search", :as => :resource_search
  match '/articles/search' => "articles#search", :as => :article_search
  
  
  
  match 'login' => 'sessions#new', :via => :get
  match 'login' => 'sessions#create', :via => :post
  match 'logout'  => 'sessions#destroy', :via => :delete
  match 'test'  =>  "testings#test", :via => :post 
  
  
  match '/classes/:id' => 'groups#show', :as => :group, :via => :get
  match '/classes/:id/topics/page(/:page)' => 'groups#show'
  match '/topics/page(/:page)' => 'topics#index'        
  match '/topics/:path/page(/:page)' => 'topics#index'
  
  
  
  match '/classes/:id'  => "groups#update", :as => :group, :via => :put
  match '/classes/:id'  => "groups#destroy", :as => :group, :via => :delete
  
  match '/classes'  => "groups#index", :as => :groups, :via => :get
  match '/classes'  => "groups#create", :as => :groups, :via => :post
  
  match '/classes/new'  => "groups#new", :as => :new_group, :via => :get
  match '/classes/:id/edit'  => "groups#edit", :as => :edit_group, :via => :get
    
  match '/classes/:group_id/topics/:id' => 'topics#show', :as => :class_topic

  
  
  match 'resources/:path' => "resources#index", :as => :category_resources
  match 'notes/:path' => "notes#index", :as => :category_notes
  match 'articles/:path' => "articles#index", :as => :category_articles
  match 'topics/:path' => "topics#index", :as => :category_topics
  
  
  match '/events/page(/:page)' => 'events#index' 
  
  match '/notes/page(/:page)' => 'notes#index'
  match '/notes/:path/page(/:page)' => 'notes#index'
  
  
  match '/articles/page(/:page)' => 'articles#index'
  match '/articles/:path/page(/:page)' => 'articles#index'
  
  
  match '/resources/page(/:page)' => 'resources#index'
  match '/resources/:path/page(/:page)' => 'resources#index'
  
  
  match '/testings/page(/:page)' => 'testings#index'
  match '/apps' => 'testings#index'
  match '/apps/:id' => 'testings#show'
  match '/apps/page(/:page)' => 'testings#index'
  
  match '/classrooms/:id/page(/:page)' => 'classrooms#show'
  match '/discussions/page(/:page)' => 'discussions#index'
  
  
  match '/people/page(/:page)' => 'people#index'
  

  
  
  

  namespace :admin do
    resources :people
  end

  

  match '*path' => proc { |env| Rails.env.development? ? (raise ActionController::RoutingError, %{No route matches "#{env["PATH_INFO"]}"}) : ApplicationController.action(:render_not_found).call(env) }  
  
end

app/models/group.rb
# -*- encoding : utf-8 -*-
class Group < ActiveRecord::Base
  belongs_to :person
  has_many :topics
  validates :name, :length => {:in => 1..20, :message => "班级字数长度在1到20之间"}
  validates :description, :length => {:in => 1..100000, :message => "描述字数在1到10万之间"}
  
  Paperclip.interpolates :avatar_date do |avatar, style|
    avatar.instance.avatar_updated_at.to_date.to_s[0,7]
  end
  
  #TODO:,图片如何加水印
  
  has_attached_file :avatar,   
          :styles => {:medium => '100x100'},
          :path => ":rails_root/public/system/:class/:attachment/#{Date.today.to_s[0,7]}/:style/:hash.:extension",
          :url => "/system/:class/:attachment/:avatar_date/:style/:hash.:extension",
          :hash_data  =>  ":id/:style/:updated_at",
          :hash_secret => "secretisnosecret"
      
   # filetype
  # TODO:必须有avatar验证
  
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/bmp','image/pjepg', 'image/x-png'], :message => "图片格式只能为jpg,png,gif,bmp", :unless => "avatar.original_filename.blank?"
  
  # and size
  validates_attachment_size :avatar, :less_than => 500.kilobytes, :message => "图片大小不能超过500kb", :unless => "avatar.original_filename.blank?"
  
end

app/controllers/groups_controller.rb
# -*- encoding : utf-8 -*-
class GroupsController < ApplicationController
  skip_before_filter :is_login?, :only => [:show]
  before_filter :only_admin_can_do, :except => [:show]

  # GET /groups/1
  # GET /groups/1.json
  def index  
   @groups = Group.includes(:person).order("created_at desc")
    respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @groups }
   end
  end
  
  def show
    @group = Group.find(params[:id])
    @topics = @group.topics.includes(:person).includes(:last_replied_person).includes(:comments).order("last_replied_at desc").page(params[:page])      
    @topic = @topic || Topic.new
    @people = Person.where(["role = ? or role = ? or role =? or role = ?", "学员", "老师", "助教", "admin"]).order("score desc").limit(12)

    @notes = Note.order("created_at desc").limit(10)
    @testings = Testing.order("created_at desc").limit(10)
    @resources = Resource.order("created_at desc").limit(10)
    @articles = Article.order("created_at desc").limit(10)
     
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
      format.rss
    end
  end

  def new
    @group = Group.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = current_person.groups.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = current_person.groups.build(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: '创建成功' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new", notice: '创建失败' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json

  def update
    @group = current_person.groups.find(params[:id])
    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: '更新成功' }
        format.json { head :no_content }
      else
        
        format.html { render action: "edit", notice: "更新失败" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = current_person.groups.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
# -*- encoding : utf-8 -*-
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h4><%= @group.errors.count.to_s+"个错误" %>:</h4>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= format_error(msg) %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


	<div class="field">
    <%= f.label :avatar, "班级图片(必填)" %><br />
    <%= f.file_field :avatar  %>
  </div>

  <div class="field">
    <%= f.label :name, "班级名(1到100字)" %><br />
    <%= f.text_field :name, :size => 113,:class => "input-xxlarge" %>
  </div>

  <div class="field">
    <%= f.label :description, "班级描述(1到10万字)" %><br />
    <%= f.text_area :description, :size => "82x18",:class => "input-xxlarge" %>
  </div>


  <div class="actions">
    <%= f.submit "提交", :class => "btn btn-primary ie6-btn" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="row">
	<div class="span8">

	<h4>修改班级信息</h4>

	<%= render 'form' %>

	</div>
	<div class="span4">

	<%= link_to '<<返回', groups_path %>
	</div>
</div>

app/views/groups/index.html.erb
<% content_for :title,"所有班级-pua课程网" %>
<% content_for :keywords,"泡妞班级列表,所有班级" %>
<% content_for :description,"pua课程网班级列表,每天推出一个班级." %>


	<% if notice %>
			<div class="alert">
			  <button type="button" class="close" data-dismiss="alert">&times;</button>
			  <%= notice %>
			</div>
		<% end %>
	
	<% if is_admin? %> 			
		<%= link_to '创建班级', new_group_path %>
	<% end %>

<div class="row">
	<h1>所有班级</h1>
	<div id="groups">		
		<% @groups.each do |group| %>
			<%= link_to image_tag(group.avatar.url(:medium), :class => "image_right_bottom"), group %>					
			
			<h4 class= "index_organization_title"><%= link_to group.name, group %></h4>
			<div class="index_organization_description"><%= truncate(group.description, :length => 55) %></div><br />
			创建时间:<%= group.created_at.to_date.to_s %>
			<span class="space">创建者:<%= link_to group.person.nick_name, :root %></span>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<% if is_admin? %>
				<%= link_to '编辑', edit_group_path(group) %>
				<%= link_to '删除', group, :data => { :confirm => '确定删除?' }, method: :delete %>
			<% end %>
			<hr />
		<% end %>
	</div>
</div>


	

app/views/groups/new.html.erb
<div class="row">
	<div class="span8">

	<h4>创建班级</h4>

	<%= render 'form' %>

	</div>
	<div class="span4">

	<%= link_to '<<返回', groups_path %>
	</div>
</div>

app/views/groups/show.html.erb
<% content_for :title,"泡妞学班级" %>
<% content_for :keywords,"话术,惯例库,追女孩子的技巧,追女孩子的短信,追女孩子的话,追女孩子的方法,追女生,追女生技巧" %>
<% content_for :description,"泡妞学班级, 如果白天老师不在教室,如果你有约会恋爱问题,请发到泡妞学班级." %>


<div class="row">
	<div class="span4">
		<div id="group_photo">
			<%= image_tag @group.avatar.url(:medium) %>
		</div>
		<div id="group_meta">
			<p>
			  <b>班级名:</b>
			  <%= @group.name %>
			</p>

			<p>
			  <b>创建者:</b>
			  <%= @group.person.nick_name %>
			</p>

			<p>
			  <b>创建时间:</b>
			  <%= @group.created_at.to_date.to_s %>
			</p>
			<% if can_delete?(@group) %>
				<%= link_to '编辑', edit_group_path(@group) %> 
			<% end %>

		</div>

		
		<div id="group_people">
			<p><b>积分前10名:</b></p>
			<% @people.each do |person| %>
				<div class="person_photo_thumb">				
					<%= link_to image_tag(person.avatar.url(:thumb)), person %> <br />
					<%= link_to person.nick_name, person %>
				</div>
			<% end %>
		</div>
		
		<div class="clear"></div>
		<br />
		<%= link_to "...所有学员", people_path %>
		<hr />
		
		<div class="latest_message_4 group_latest_messages">
			<p><b>最近发布惯例:</b></p>
			<ul>
				<% @notes.each do |note| %>
					<li><%= link_to note.title, note %><br /></li>
				<% end %>				
			</ul>
			<br />
			<%= link_to "...所有惯例", notes_path %>
		</div>
		<hr />
		
		<div class="latest_message_4 group_latest_messages">
			<p><b>最近发布测试:</b></p>
			<ul>
				<% @testings.each do |testing| %>
					<li><%= link_to testing.title, testing %><br /></li>
				<% end %>				
			</ul>
			<br />
			<%= link_to "...所有测试", testings_path %>
		</div>
		<hr />
		
		
		<div class="latest_message_4 group_latest_messages latest_resources">
			<p><b>最近发布资源:</b></p>
			<ul>
				<% @resources.each do |resource| %>
					<li><%= image_tag resource.category.avatar.url(:thumb) %><%= link_to resource.title, resource %><br /></li>
				<% end %>				
			</ul>
			<br />
			<%= link_to "...所有资源", resources_path %>
		</div>
		<hr />
		
		<div class="latest_message_4 group_latest_messages">
			<p><b>最近发布文章:</b></p>
			<ul>
				<% @articles.each do |article| %>
					<li><%= link_to article.title, article %><br /></li>
				<% end %>				
			</ul>
			<br />
			<%= link_to "...所有文章", articles_path %>
		</div>		
	</div>
		
	
	<div class="span8">
		<h4>发帖(有问必答,老师每晚9点回复)</h4>		
		<% if notice %>
			<div class="alert">
			  <button type="button" class="close" data-dismiss="alert">&times;</button>
			  <%= notice %>
			</div>
		<% end %>
	
		<%= render :partial => 'topics/form' %>
		<h4>最近回复</h4>
		
		<% @topics.each do |topic| %>
			<div class="entry_person_photo">
				<%= image_tag topic.person.avatar.url(:thumb) %>
			</div>
			<div class="entry_title"><%= link_to topic.title, class_topic_path(@group,topic), :target => "_blank" %></div>
			<br /><br />
			<div class="entry_meta">发布:<%= link_to topic.person.nick_name, topic.person %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;时间:<%= topic.created_at.to_date.to_s %>
			</div>
			
			<div class="entry_content"><%= simple_format truncate(topic.content, :length => 200) %></div>
			<div class="entry_edit_bar">
				
				<% if topic.comments.size > 0 %>
					<span class="gray">最后回复于<%= time_ago_in_words(topic.last_replied_at) %>, 来自</span><%= link_to  topic.last_replied_person.nick_name, topic.last_replied_person %>
				<% end %>
				<div class="right_text"><%= link_to "(#{topic.comments.size})回复", class_topic_path(@group,topic), :target => "_blank"  %></div>
			</div>
			<hr />
		<% end %>
		<%= paginate @topics %>		
	</div>
</div>