config/routes.rb
V8::Application.routes.draw do

  resources :options

  root :to => 'topics#index' 

  match 'guangpan' => 'pages#guangpan'
  match 'baodao' => 'pages#baodao'
  match 'zhinanzhen' => 'pages#zhinanzhen'
  match 'zhidao'  => "pages#zhidao"
  match 'xianchang'  => "pages#xianchang"
  match 'xianchang/page(/:page)'  => "pages#xianchang"
  match 'wangpan'  => "pages#wangpan"
  match 'xingxiang'  => "pages#xingxiang"
  match 'vip' => "pages#vip"
  match 'xingxiang' => "pages#xingxiang"
  match 'hezuo' => "pages#hezuo"

  
    
  
  
  resources  :discussions, :comments, :subjects

  
  resources :topics,:constraints => {:id => /\d+/}  do
    resources :comments
  end
  
  resources :classrooms do
    resources :discussions
  end

  resources :notes, :constraints => {:id => /\d+/} do
    resources :comments
  end

  resources :resources, :constraints => {:id => /\d+/} do
    resources :comments
  end

  resources :testings do
    resources :comments
  end

  resources :articles, :constraints => {:id => /\d+/} do
    resources :comments
  end
  
  resources :events do 
    resources :notes
  end
  
  resources :subjects do
    resources :events
  end

  resources :categories do
    resources :articles
    resources :resources
    resources :notes  
    resources :topics
  end
  
  resources :people do
    resources :subjects
  end
  
  match '/topics/search' => "topics#search", :as => :topic_search
  match '/notes/search' => "notes#search", :as => :note_search
  match '/resources/search' => "resources#search", :as => :resource_search
  match '/articles/search' => "articles#search", :as => :article_search
  
  
  
  match 'login' => 'sessions#new', :via => :get
  match 'login' => 'sessions#create', :via => :post
  match 'logout'  => 'sessions#destroy', :via => :delete
  match 'test'  =>  "testings#test", :via => :post 
  
  
  match '/classes/:id' => 'groups#show', :as => :group, :via => :get
  match '/classes/:id/topics/page(/:page)' => 'groups#show'
  match '/topics/page(/:page)' => 'topics#index'        
  match '/topics/:path/page(/:page)' => 'topics#index'
  
  
  
  match '/classes/:id'  => "groups#update", :as => :group, :via => :put
  match '/classes/:id'  => "groups#destroy", :as => :group, :via => :delete
  
  match '/classes'  => "groups#index", :as => :groups, :via => :get
  match '/classes'  => "groups#create", :as => :groups, :via => :post
  
  match '/classes/new'  => "groups#new", :as => :new_group, :via => :get
  match '/classes/:id/edit'  => "groups#edit", :as => :edit_group, :via => :get
    
  match '/classes/:group_id/topics/:id' => 'topics#show', :as => :class_topic

  
  
  match 'resources/:path' => "resources#index", :as => :category_resources
  match 'notes/:path' => "notes#index", :as => :category_notes
  match 'articles/:path' => "articles#index", :as => :category_articles
  match 'topics/:path' => "topics#index", :as => :category_topics
  
  
  match '/events/page(/:page)' => 'events#index' 
  
  match '/notes/page(/:page)' => 'notes#index'
  match '/notes/:path/page(/:page)' => 'notes#index'
  
  
  match '/articles/page(/:page)' => 'articles#index'
  match '/articles/:path/page(/:page)' => 'articles#index'
  
  
  match '/resources/page(/:page)' => 'resources#index'
  match '/resources/:path/page(/:page)' => 'resources#index'
  
  
  match '/testings/page(/:page)' => 'testings#index'
  match '/apps' => 'testings#index'
  match '/apps/:id' => 'testings#show'
  match '/apps/page(/:page)' => 'testings#index'
  
  match '/classrooms/:id/page(/:page)' => 'classrooms#show'
  match '/discussions/page(/:page)' => 'discussions#index'
  
  
  match '/people/page(/:page)' => 'people#index'
  

  
  
  

  namespace :admin do
    resources :people
  end

  

  match '*path' => proc { |env| Rails.env.development? ? (raise ActionController::RoutingError, %{No route matches "#{env["PATH_INFO"]}"}) : ApplicationController.action(:render_not_found).call(env) }  
  
end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
	<% if @resource.errors.any? %>
			<div class="alert">
			  <button type="button" class="close" data-dismiss="alert">&times;</button>
			  <h4><%= @resource.errors.count.to_s+"个错误" %> :</h4>
	      <ul>
	      <% @resource.errors.full_messages.each do |msg| %>
	        <li><%= format_error(msg) %></li>
	      <% end %>
	      </ul>
			</div>
	  <% end %>
	

  <div class="field">
    <%= f.label :category_id, "选择类别" %>
    <%= f.select :category_id, collect_resource_categories_for_select,:selected => 21 %>
  </div>

  <div class="field">
    <%= f.label :title, "标题(1到100字)" %>
    <%= f.text_field :title, :class => "input-xxlarge" %>
  </div>
  
  <div class="field">
    <%= f.label :download_link, "下载链接" %><span class="help-inline">(先上传到这些站再复制下载网址.<a href="http://www.dbank.com">数据银行</a>,<a href="http://ishare.iask.sina.com.cn/">sina共享</a>,<a href="http://wenku.baidu.com/">百度文库</a>或<a href="http://yun.baidu.com">百度网盘</a>)</span>
    <%= f.text_area :download_link, :size => "72x3", :class => "input-xxlarge" %>
  </div>


  <div class="actions"> 
		<%= f.submit "提交", :class => "btn btn-primary ie6-btn" %> 
		<%= link_to '取消', resources_path, :class => "btn cancel" %>
		
	</div> 
<% end %>

app/views/resources/edit.html.erb
<div class="row">
	<div class="span8">
		<h4>编辑资源</h4>

		<%= render 'form' %>

		<%= link_to '取消', resources_path %>

	</div>
	
</div>

app/views/resources/index.html.erb
<% content_for :title,"国内外最经典的泡妞书籍泡妞电影-泡妞书籍大全-泡妞书籍下载" %>
<% content_for :keywords,"泡妞秘籍,泡妞电影,泡妞视频,泡妞书籍,泡妞电子文档." %>
<% content_for :description,"你还在网上到处搜索泡妞书籍吗?所有的国内外最经典泡妞书籍都在这里,并且常常更新.把妹达人,冷读术,迷男方法,约会倍增术,身体语言密码,恋爱方程式,逆向恋爱术,现实世界诱惑术,杂耍人方法,
David_x方法, 把妹大人之游戏规则.你不可不知的情场致胜秘密.男人来自火星,女人来自金星,魔法诱惑等,以及一些保密文档." %>

<div class="row ie6-row">
	<div class="span9">		
 	
		<% if notice %>
			<div class="alert">
			  <button type="button" class="close" data-dismiss="alert">&times;</button>
			  <%= notice %>
			</div>
		<% end %>
		                
		 <%= link_to "+ 分享资源",:new_resource, :class => "btn btn-success pull-left" %>
    <%= form_tag :resource_search, :class => "form-search pull-right" do |f| %>
	    <%= text_field_tag :query,nil, :class => "input-medium search-query" %>
  		<button type="submit" class="btn btn-primary">搜索资源</button>
		<% end %>
		<br />
		<br />
		<h4>最近资源分享</h4>
		<table id="search_results" class="table table-condensed">
			</thead>
			<tbody>
				<% @resources.each do |resource| %>
				<tr>
					<td class="resource-avatar"><%= image_tag resource.category.avatar.url(:thumb) %></td>
					
					<td class="title"><%= link_to resource.title, resource , :target => "_blank"%></td>
					
					<td class="created-at"><%= resource.created_at.to_date.to_s %></td>
					<td class="nick_name"><%= link_to resource.person.nick_name, resource.person %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		
		<%= paginate @resources %>		
	</div>
	
	
	
	<div class="span3">	
		<ul class="nav nav-tabs nav-stacked">
			<li <%="class=active" if @path == nil  %>><%= link_to resources_path do %><i class="icon-chevron-right pull-right"></i>所有资源<% end %></li>
			<% @categories.each do |category| %>
			<li <%="class=active" if @path == category.path  %>>
			<%= link_to category_resources_path(:path => category.path) do %>
				<i class="icon-chevron-right pull-right"></i><%= image_tag category.avatar.url(:thumb) %><%= category.name %>(<%= category.resources.size %>)
			<% end %>
			</li>
			<% end %>
		</ul>
		<hr />
		<h4>标签(国内pua)</h4>
		<ul class="ie6-label">
				<li class="label label-info"><%= link_to "七烟",resource_search_path(:query => "七烟") %></li>
				<li class="label label-info"><%= link_to "寒江雪",resource_search_path(:query => "寒江雪") %></li>
				<li class="label label-info"><%= link_to "郑匡宇",resource_search_path(:query => "郑匡宇") %></li>
				<li class="label label-info"><%= link_to "成真",resource_search_path(:query => "成真") %></li>
				<li class="label label-info"><%= link_to "淘宝猎手",resource_search_path(:query => "淘宝猎手") %></li>
				<li class="label label-info"><%= link_to "冷爱",resource_search_path(:query => "冷爱") %></li>
				<li class="label label-info"><%= link_to "魔鬼咨询师",resource_search_path(:query => "魔鬼咨询师") %></li>
				<li class="label label-info"><%= link_to "Q帝",resource_search_path(:query => "Q帝") %></li>
				<li class="label label-info"><%= link_to "tango",resource_search_path(:query => "tango") %></li>
				<li class="label label-info"><%= link_to "CYD",resource_search_path(:query => "CYD") %></li>
				<li class="label label-info"><%= link_to "公主",resource_search_path(:query => "公主") %></li>
				<li class="label label-info"><%= link_to "Cris",resource_search_path(:query => "Cris") %></li>
				<li class="label label-info"><%= link_to "但丁",resource_search_path(:query => "但丁") %></li>
				<li class="label label-info"><%= link_to "Highly-Guest",resource_search_path(:query => "Highly-Guest") %></li>
				<li class="label label-info"><%= link_to "痴情男",resource_search_path(:query => "痴情男") %></li>
				<li class="label label-info"><%= link_to "PUA三人行",resource_search_path(:query => "PUA三人行") %></li>
				<li class="label label-info"><%= link_to "安迪",resource_search_path(:query => "安迪") %></li>
				<li class="label label-info"><%= link_to "妖精",resource_search_path(:query => "妖精") %></li>
				<li class="label label-info"><%= link_to "玫瑰有约",resource_search_path(:query => "玫瑰有约") %></li>
				<li class="label label-info"><%= link_to "墨菲斯",resource_search_path(:query => "墨菲斯") %></li>
				<li class="label label-info"><%= link_to "龙语墨",resource_search_path(:query => "龙语墨") %></li>
				<li class="label label-info"><%= link_to "你不是一个人七夕",resource_search_path(:query => "你不是一个人七夕") %></li>				
				<li class="label label-info"><%= link_to "女语者",resource_search_path(:query => "女语者") %></li>
				<li class="label label-info"><%= link_to "老贾",resource_search_path(:query => "老贾") %></li>
				<li class="label label-info"><%= link_to "路易",resource_search_path(:query => "路易") %></li>
				<li class="label label-info"><%= link_to "海沟",resource_search_path(:query => "海沟") %></li>
				<li class="label label-info"><%= link_to "小狗",resource_search_path(:query => "小狗") %></li>
				<li class="label label-info"><%= link_to "面具",resource_search_path(:query => "面具") %></li>
				<li class="label label-info"><%= link_to "无情",resource_search_path(:query => "无情") %></li>
				<li class="label label-info"><%= link_to "蓝色答案",resource_search_path(:query => "蓝色答案") %></li>
				<li class="label label-info"><%= link_to "浪迹",resource_search_path(:query => "浪迹") %></li>
				<li class="label label-info"><%= link_to "神曲",resource_search_path(:query => "神曲") %></li>
				<li class="label label-info"><%= link_to "小杰",resource_search_path(:query => "小杰") %></li>
				<li class="label label-info"><%= link_to "真命舞者",resource_search_path(:query => "真命舞者") %></li>
				<li class="label label-info"><%= link_to "子陵",resource_search_path(:query => "子陵") %></li>
				
			</ul>
			<hr />


			<h4>标签(约会指导书籍)</h4>
			<ul class="ie6-label" >
				<li class="label label-info"><%= link_to "超级异性吸引术",resource_search_path(:query => "超级异性吸引术") %></li>
				<li class="label label-info"><%= link_to "迷上我",resource_search_path(:query => "迷上我") %></li>
				<li class="label label-info"><%= link_to "逆向恋爱术",resource_search_path(:query => "逆向恋爱术") %></li>
				<li class="label label-info"><%= link_to "正妹心理学",resource_search_path(:query => "正妹心理学") %></li>
				<li class="label label-info"><%= link_to "搭讪圣经",resource_search_path(:query => "搭讪圣经") %></li>
				<li class="label label-info"><%= link_to "正妹心理学",resource_search_path(:query => "正妹心理学") %></li>
				<li class="label label-info"><%= link_to "脱离好人",resource_search_path(:query => "脱离好人") %></li>
				<li class="label label-info"><%= link_to "约会倍增术",resource_search_path(:query => "约会倍增术") %></li>
				<li class="label label-info"><%= link_to "谜男方法",resource_search_path(:query => "谜男方法") %></li>
				<li class="label label-info"><%= link_to "杂耍人方法",resource_search_path(:query => "杂耍人") %></li>
				<li class="label label-info"><%= link_to "david_x方法",resource_search_path(:query => "david_x方法") %></li>
				<li class="label label-info"><%= link_to "现实世界诱惑术",resource_search_path(:query => "现实世界诱惑术") %></li>
				<li class="label label-info"><%= link_to "把妹达人",resource_search_path(:query => "把妹达人") %></li>
				<li class="label label-info"><%= link_to "把妹达人2游戏规则",resource_search_path(:query => "把妹达人2游戏规则") %></li>
				<li class="label label-info"><%= link_to "瞬间赢得信任的冷读术",resource_search_path(:query => "瞬间赢得信任的冷读术") %></li>
				<li class="label label-info"><%= link_to "你不可不知的情场制胜秘密",resource_search_path(:query => "你不可不知的情场制胜秘密") %></li>
				<li class="label label-info"><%= link_to "男人来自火星，女人来自金星",resource_search_path(:query => "男人来自火星，女人来自金星") %></li>
				
				<li class="label label-info"><%= link_to "约会经济学",resource_search_path(:query => "约会经济学") %></li>
			</ul>			    
			<hr />
			
			
			<h4>标签(词语)</h4>
			<ul class="ie6-label">
				<li class="label label-info"><%= link_to "pua",resource_search_path(:query => "pua") %></li>
				<li class="label label-info"><%= link_to "短信",resource_search_path(:query => "短信") %></li>
				<li class="label label-info"><%= link_to "电话",resource_search_path(:query => "电话") %></li>
				<li class="label label-info"><%= link_to "游戏",resource_search_path(:query => "游戏") %></li>
				<li class="label label-info"><%= link_to "惯例",resource_search_path(:query => "惯例") %></li>
				<li class="label label-info"><%= link_to "搭讪教主",resource_search_path(:query => "搭讪教主") %></li>
				<li class="label label-info"><%= link_to "搭讪",resource_search_path(:query => "搭讪") %></li>
				<li class="label label-info"><%= link_to "正妹",resource_search_path(:query => "正妹") %></li>
				<li class="label label-info"><%= link_to "把妹教学",resource_search_path(:query => "把妹教学") %></li>
				<li class="label label-info"><%= link_to "泡妞高手",resource_search_path(:query => "泡妞高手") %></li>
				<li class="label label-info"><%= link_to "约会培训",resource_search_path(:query => "约会培训") %></li>
				<li class="label label-info"><%= link_to "恋爱高手",resource_search_path(:query => "恋爱高手") %></li>
				<li class="label label-info"><%= link_to "坏男人",resource_search_path(:query => "坏男人") %></li>
				<li class="label label-info"><%= link_to "笑话",resource_search_path(:query => "笑话") %></li>
				<li class="label label-info"><%= link_to "接吻",resource_search_path(:query => "接吻") %></li>
				<li class="label label-info"><%= link_to "约会培训",resource_search_path(:query => "约会培训") %></li>
				<li class="label label-info"><%= link_to "追女孩子的技巧",resource_search_path(:query => "追女孩子的技巧") %></li>
				<li class="label label-info"><%= link_to "kino",resource_search_path(:query => "kino") %></li>
				<li class="label label-info"><%= link_to "泡妞秘籍",resource_search_path(:query => "泡妞秘籍") %></li>
				<li class="label label-info"><%= link_to "约会学",resource_search_path(:query => "约会学") %></li>
				<li class="label label-info"><%= link_to "心理学",resource_search_path(:query => "心理学") %></li>
				<li class="label label-info"><%= link_to "催眠",resource_search_path(:query => "催眠") %></li>
				<li class="label label-info"><%= link_to "吸引",resource_search_path(:query => "吸引") %></li>
				<li class="label label-info"><%= link_to "幽默",resource_search_path(:query => "幽默") %></li>
				<li class="label label-info"><%= link_to "上床",resource_search_path(:query => "上床") %></li>
				<li class="label label-info"><%= link_to "少妇",resource_search_path(:query => "少妇") %></li>
		</ul>
	</div>

	
</div>  <!-- end of box -->

app/views/resources/new.html.erb
<div class="row">
	<div class="span8">

	<h4>分享资源</h4>

	<%= render 'form' %>

	</div>
	<div class="span4">

	<%= link_to '<<返回', resources_path %>
	</div>
</div>

app/views/resources/search.html.erb
<% content_for :title,"资源搜索" %>
<% content_for :keywords,"泡妞学问答,泡妞问题,泡妞案例分享." %>
<% content_for :description, "资源搜索" %>

<div class="row">		
	<div class="span8">
		<% if notice %>
			<div class="alert">
			  <button type="button" class="close" data-dismiss="alert">&times;</button>
			  <%= notice %>
			</div>
		<% end %>
		<div class="row">
			<div class="span8">
				<%= form_tag :resource_search, :class => "form-search" do |f| %>
			    <%= text_field_tag :query,params[:query], :class => "input-medium search-query" %>
		  		<button type="submit" class="btn btn-primary">搜索资源</button>
				<% end %>
			</div>
		</div>
		
		<h4>资源搜索:<%= params[:query] %></h4>
		<table id="search_results" class="table table-condensed">
			</thead>
			<tbody>
				<% @resources.each do |resource| %>
				<tr>
					<td class="resource-avatar"><%= image_tag resource.category.avatar.url(:thumb) %></td>
					
					<td class="title"><%= link_to resource.title, resource , :target => "_blank"%></td>
					
					<td class="created-at"><%= resource.created_at.to_date.to_s %></td>
					<td class="nick_name"><%= link_to resource.person.nick_name, resource.person %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<% unless @resources == [] %>
			<%= paginate @resources %>		
		<% end %>
	</div>
	
	
	
	<div class="span4">
		<%= link_to "返回<<", resources_path %>
	</div>

</div>

app/views/resources/show.html.erb
<% content_for :title, @resource.title %>
<% content_for :keywords,"国外泡妞书籍,台湾泡妞书籍,大陆泡妞书籍,泡妞案例,泡妞电影,泡妞图片,追女孩子的短信,搭讪技术,冷读术,接吻技巧,接吻的视频教程,泡妞小说大全,相亲" %>
<% content_for :description, @resource.title %>




<div class="row">
	<div class="span8">
		<% if notice %>
			<div class="alert">
			  <button type="button" class="close" data-dismiss="alert">&times;</button>
			  <%= notice %>
			</div>
		<% end %>
		<div class="media">
		  <a class="pull-left" href="#">
				<%= image_tag @resource.person.avatar.url(:thumb),:class => "media-object" %>
		  </a>
		  <div class="media-body">
		    <h4 class="media-heading"><%= link_to @resource.title, @resource, :target => "_blank" %></h4>
		    <div class="media">
					发布:<%= link_to @resource.person.nick_name, @resource.person %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;类别:<%= link_to @resource.category.name, category_resources_path(:path => @resource.category.path) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;时间:<%= @resource.created_at.to_date.to_s %>
					<br />
					<br />     
					<p>下载链接:</p>
					<p>     
						 <% if !is_member? and [16,21].include?(@resource.category_id) %>
							<h5>抱歉,你不能下载vip资源,请联系qq:399906796, <%= link_to "开通vip学员", "/vip" %></h5>
						 <% else %>
						  <%= link_to word_wrap(@resource.download_link), @resource.download_link %>
						 <% end %>
					</p>
						
					
					<% if can_delete?(@resource) %>
						<%= link_to '编辑', edit_resource_path(@resource) %>
						<%= link_to '删除', @resource, :data => { :confirm => '确定删除' }, method: :delete %>
					<% end %>
					<%= render :partial => "share/bdshare" %>	
					
		    </div>
		  </div>
		</div>
		
		<br />
		<h4>所有评论(评论:+1积分)</h4>
		
		<hr />
		
		<div id="comments">
			<% @comments.each do |comment| %>
				<%= render comment %>
			<% end %>
			
			<%= render :partial => "comments/form", :locals => { :comment => @comment, :commable_type => "Resource", :commable_id => @resource.id } %>
		</div>
			
	</div>
	<div class="span4">
		<%= link_to "返回<<", :back %>
		<hr />
		<h4>最近资源</h4>
		<ul>
		<% @latest_resources.each do |resource| %>
			<li><%= link_to resource.title, resource %></li>
		<% end %>
		</ul>
	</div>
</div>